language: java
jdk:
  - openjdk15

addons:
  sonarcloud:
    organization: matteo-coni
    token: c15bbb12f80fc0d6a2250c739eb1f46801d72436
  apt:
    packages:
      - openjfx

script: 
  - ant build
  - sonar-scanner
